from fastapi.responses import HTMLResponse
from . import fast_scalper_beta_001_legacy as legacy

HTML = r'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Fast Scalper Beta</title><style>
*{box-sizing:border-box}html,body{margin:0;background:#080e1b;color:#edf2ff;font-family:Arial,Helvetica,sans-serif}body{min-height:100vh}.wrap{max-width:720px;margin:0 auto;padding:16px 25px 36px}.head{margin:0 0 18px}.head h1{font-size:31px;line-height:1.05;margin:0;font-weight:800;letter-spacing:-.6px}.bolt{font-size:42px;vertical-align:-5px;margin-right:7px}.sub{font-size:18px;color:#8d98b1;margin-top:8px}.card{background:#111a2d;border:1px solid #273653;border-radius:25px;padding:25px 25px 23px;margin:0 0 18px}.grid2{display:grid;grid-template-columns:1fr 1fr;gap:14px}.metric{background:#0a1223;border-radius:17px;padding:18px;min-height:92px}.metric .k{font-size:18px;margin-bottom:5px}.metric .v{font-size:25px;font-weight:800}.modeBtns{display:grid;grid-template-columns:1fr 1fr 1.25fr;gap:14px;margin-top:17px}.row{display:flex;gap:14px;align-items:center;margin-top:14px}.label{font-size:16px;font-weight:800;color:#8d98b1;margin:15px 0 7px;letter-spacing:.3px}.input{height:54px;background:#091122;border:1px solid #30405e;border-radius:15px;color:#edf2ff;padding:0 17px;font-size:18px;outline:none;width:100%}.btn{height:54px;border:0;border-radius:15px;padding:0 22px;color:#fff;font-weight:800;font-size:17px;background:#245b91;white-space:nowrap}.btn.green{background:#00a65a}.btn.red{background:#b52f45}.btn.gray{background:#273753}.modeBtns .btn:first-child{background:#293954}.check{font-size:18px;display:flex;align-items:center;gap:9px;white-space:nowrap}.check input{width:27px;height:27px;accent-color:#1676e8}.profitRow{display:flex;gap:14px;align-items:center}.profitRow .input{flex:1}.mainBtns{display:grid;grid-template-columns:1.35fr 1fr .72fr;gap:14px;margin-top:14px}.offRow{display:flex;align-items:center;gap:14px;margin-top:14px}.offRow .btn{width:147px}.session{font-size:17px;color:#9ba5ba}.note{font-size:17px;color:#9ba5ba;line-height:1.35;margin-top:15px}.status{font-size:14px;color:#9ba5ba;min-height:18px;margin-top:8px}.sectionTitle{font-size:28px;font-weight:800;margin:0 0 18px}.badge{display:inline-block;background:#b52f45;color:#fff;border-radius:14px;padding:8px 16px;font-size:14px;font-weight:800;margin-bottom:14px}.pos{display:flex;flex-direction:column;gap:10px}.pitem{background:#0a1223;border-radius:14px;padding:12px 14px;font-size:14px}.empty{color:#8d96a9;font-size:17px}.slots{display:grid;grid-template-columns:1fr 1fr;gap:12px}.slot{height:52px;background:#091122;border:1px solid #30405e;border-radius:14px;color:#8d96a9;padding:0 16px;font-size:17px;width:100%}@media(max-width:560px){.wrap{padding:16px 25px 32px}.modeBtns{gap:12px}.modeBtns .btn{padding:0 10px}.mainBtns{gap:12px}.mainBtns .btn{padding:0 12px}.label{font-size:15px}}
</style></head><body><div class="wrap">
<div class="head"><h1><span class="bolt">⚡</span>Fast Scalper Beta</h1><div class="sub">Version 0.01 REPAIR PAPER · Trading TF: 3m</div></div>
<section class="card"><div class="grid2"><div class="metric"><div class="k">Account Balance</div><div class="v" id="account">1850.0000</div></div><div class="metric"><div class="k">Bot Balance</div><div class="v" id="bot">0.0000</div></div><div class="metric"><div class="k">Reserve</div><div class="v" id="reserve">0.0000</div></div><div class="metric"><div class="k">Session PnL</div><div class="v" id="pnl">0.0000</div></div></div><div class="modeBtns"><button class="btn" onclick="setMode('PAPER')">PAPER</button><button class="btn" onclick="setMode('BINANCE_TEST')">BINANCE<br>TEST</button><button class="btn" onclick="testBinance()">TEST BINANCE</button></div><div class="note" id="modeNote">Bot balance set: 0.0000 USDT</div></section>
<section class="card"><div class="label">BOT BALANCE · USDT</div><div class="row" style="margin-top:0"><input id="allocation" class="input" inputmode="decimal" placeholder="150"><button class="btn" onclick="setAllocation()">SET BOT BALANCE</button></div><div class="label">WITHDRAW AMOUNT · USDT</div><div class="row" style="margin-top:0"><input id="withdraw" class="input" inputmode="decimal" placeholder="0.00"><button class="btn red" onclick="withdraw()">WITHDRAW</button></div><div class="label">PROFIT TARGET · %</div><div class="profitRow"><input id="profit" class="input" inputmode="decimal" value="0.33"><label class="check"><input id="reinvest" type="checkbox" checked> Reinvest</label></div><div class="mainBtns"><button class="btn green" onclick="startBot()">BOT ON · ACTIVE</button><button class="btn red" onclick="emergency()">EMERGENCY</button><button class="btn gray" onclick="resetBot()">RESET</button></div><div class="offRow"><button class="btn red" onclick="stopBot()">BOT OFF</button><div class="session" id="session">SESSION 00:00 · 24H 00:00</div></div><div class="status" id="status"></div></section>
<section class="card"><div class="sectionTitle">Open Positions</div><div id="botStatus" class="badge">BOT OFF · TRADING STOPPED</div><div class="pos" id="positions"><div class="empty">No open positions.</div></div></section>
<section class="card"><div class="sectionTitle">Rotation Pool · TOP-20</div><div class="slots" id="slots"></div></section>
</div><script>
const $=id=>document.getElementById(id);const api=async(path,opts={})=>{const r=await fetch(path,{cache:'no-store',headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.detail||d.error||('HTTP '+r.status));return d};function val(x){return Number(x||0).toFixed(4)}function age(s){s=Math.max(0,Math.floor(Number(s||0)));return String(Math.floor(s/3600)).padStart(2,'0')+':'+String(Math.floor(s%3600/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}function msg(t){$('status').textContent=t||''}
async function refresh(){try{const s=await api('/api/state');$('account').textContent=val(s.account);$('bot').textContent=val(s.bot_balance);$('reserve').textContent=val(s.reserve);$('pnl').textContent=val(s.session_realized);$('profit').value=Number(s.profit_pct??.33).toFixed(2);$('reinvest').checked=!!s.reinvest;$('session').textContent='SESSION '+age(s.session_age)+' · 24H '+age(s.day_age);$('modeNote').textContent='Bot balance set: '+val(s.bot_balance)+' USDT';$('botStatus').textContent=s.running?'BOT ON · ACTIVE':'BOT OFF · TRADING STOPPED';$('botStatus').style.background=s.running?'#00a65a':'#b52f45';renderSlots(s.slots||[]);renderPositions(s.positions||[]);if(s.error)msg(s.error)}catch(e){msg(e.message)}}
function renderSlots(a){const el=$('slots');if(el.children.length===20){for(let i=0;i<20;i++)el.children[i].value=a[i]||'';return}el.innerHTML='';for(let i=0;i<20;i++){const x=document.createElement('input');x.className='slot';x.value=a[i]||'';x.placeholder='USDT pair';x.addEventListener('change',saveSlots);el.appendChild(x)}}let timer;function saveSlots(){clearTimeout(timer);timer=setTimeout(async()=>{try{const a=[...document.querySelectorAll('.slot')].map(x=>x.value.trim().toUpperCase()).filter(Boolean);await api('/api/slots',{method:'POST',body:JSON.stringify({slots:a,profit_pct:Number($('profit').value.replace(',','.'))||.33,reinvest:$('reinvest').checked})};msg('Rotation Pool saved')}catch(e){msg(e.message)}},250)}
function renderPositions(a){const el=$('positions');if(!a.length){el.innerHTML='<div class="empty">No open positions.</div>';return}el.innerHTML=a.map(p=>`<div class="pitem"><b>${p.symbol}</b> · stake ${val(p.stake)} · PnL ${val(p.delta_usdt)} · age ${age(p.age_seconds)}</div>`).join('')}
async function setMode(mode){try{await api('/api/mode',{method:'POST',body:JSON.stringify({mode})});msg('Mode set: '+mode);await refresh()}catch(e){msg(e.message)}}async function testBinance(){try{const d=await api('/api/test-binance',{method:'POST'});msg(d.message||'Binance Testnet connection OK')}catch(e){msg(e.message)}}async function setAllocation(){try{const n=Number($('allocation').value.replace(',','.'));await api('/api/allocation',{method:'POST',body:JSON.stringify({amount:n})});msg('Bot balance set');await refresh()}catch(e){msg(e.message)}}async function withdraw(){try{const n=Number($('withdraw').value.replace(',','.'));await api('/api/withdraw',{method:'POST',body:JSON.stringify({amount:n})});$('withdraw').value='';msg('Withdraw completed');await refresh()}catch(e){msg(e.message)}}async function startBot(){try{await api('/api/paper/start',{method:'POST',body:JSON.stringify({profit_pct:Number($('profit').value.replace(',','.'))||0,reinvest:$('reinvest').checked})});msg('Bot active');await refresh()}catch(e){msg(e.message)}}async function stopBot(){try{await api('/api/paper/stop',{method:'POST'});msg('Bot OFF — new entries stopped');await refresh()}catch(e){msg(e.message)}}async function emergency(){try{await api('/api/paper/emergency',{method:'POST'});msg('Emergency stop completed');await refresh()}catch(e){msg(e.message)}}async function resetBot(){try{await api('/api/reset',{method:'POST'});msg('Reset completed');await refresh()}catch(e){msg(e.message)}}refresh();setInterval(refresh,1000);
</script></body></html>'''

for r in list(legacy.app.router.routes):
    if getattr(r,'path',None)=='/' and 'GET' in (getattr(r,'methods',set()) or set()):
        legacy.app.router.routes.remove(r)

@legacy.app.get('/',response_class=HTMLResponse)
async def approved_ui_home():
    response=HTMLResponse(HTML)
    response.headers['Cache-Control']='no-store, no-cache, must-revalidate, max-age=0'
    response.headers['Pragma']='no-cache'
    response.headers['Expires']='0'
    return response

print('FAST_SCALPER_APPROVED_UI_FINAL=1 ROTATION_POOL=20 TRADE_SLOTS=10 TP_DEFAULT=0.33',flush=True)
