from __future__ import annotations
import json,time
from typing import Any
from fastapi import HTTPException
from fastapi.responses import HTMLResponse
from . import fixed_app as core
from .fixed_app import app
from .paper_engine import snapshot
from .exchange_gateway import gateway

def price(symbol):
 try:return float(gateway('binance').exchange.fetch_ticker(symbol).get('last') or 0)
 except Exception:return 0.0

def report(mode:str)->dict[str,Any]:
 mode=mode.upper()
 if mode=='PAPER':
  s=snapshot(); initial=float(s.get('initial_balance') or 0); free=float(s.get('balance') or 0); positions=[]
  for symbol,p in (s.get('open_positions') or {}).items():
   px=price(symbol); qty=float(p.get('amount') or 0); entry=float(p.get('entry_price') or 0); value=qty*px if px else float(p.get('allocated_usdt') or 0); cap=float(p.get('allocated_usdt') or 0)
   positions.append({**p,'current_price':px,'market_value':value,'unrealized_pnl':value-cap,'age_sec':max(0,time.time()-float(p.get('opened_ts') or time.time())),'stage':p.get('stage','OPEN')})
  equity=free+sum(float(p.get('market_value') or 0) for p in positions); realized=float(s.get('pnl') or 0)
  return {'mode':'PAPER','running':bool(s.get('running')),'started_at':s.get('started_at'),'stopped_at':s.get('stopped_at'),'initial_balance':initial,'free_usdt':free,'equity_usdt':equity,'realized_pnl':realized,'unrealized_pnl':equity-initial-realized,'net_pnl':equity-initial,'positions':positions,'orders':list((s.get('orders') or {}).values()),'trades':list(s.get('trades') or [])[-50:],'config':s.get('config') or {},'stop_type':s.get('stop_type'),'error':s.get('error')}
 try:state=json.loads(core.LIVE_STATE.read_text()) if core.LIVE_STATE.exists() else {}
 except Exception:state={}
 positions=[]
 for symbol,p in (state.get('positions') or {}).items():
  px=price(symbol); qty=float(p.get('amount') or 0); cap=float(p.get('capital') or 0); value=qty*px if px else cap
  positions.append({**p,'current_price':px,'market_value':value,'unrealized_pnl':value-cap,'age_sec':max(0,time.time()-float(p.get('opened') or time.time())),'stage':'OPEN'})
 free=float(state.get('free_capital') or 0); initial=float(state.get('capital') or 0); equity=free+sum(float(p.get('market_value') or 0) for p in positions); realized=float(state.get('realized_pnl') or 0)
 running=bool(core.LIVE_PROC and core.LIVE_PROC.poll() is None)
 return {'mode':'LIVE','running':running,'started_at':state.get('started_at'),'stopped_at':state.get('stopped_at'),'initial_balance':initial,'free_usdt':free,'equity_usdt':equity,'realized_pnl':realized,'unrealized_pnl':equity-initial-realized,'net_pnl':equity-initial,'positions':positions,'orders':list((state.get('orders') or {}).values()),'trades':list(state.get('trades') or [])[-50:],'config':state.get('config') or {},'stop_type':state.get('stop_type'),'error':state.get('error')}

@app.get('/api/session/report/{mode}')
def session_report(mode:str):
 if mode.upper() not in {'PAPER','LIVE'}:raise HTTPException(400,'Unknown mode')
 return report(mode)
for r in list(app.router.routes):
 if getattr(r,'path',None)=='/' and getattr(r,'methods',None) and 'GET' in r.methods:app.router.routes.remove(r)

HTML=r'''<!doctype html><html lang="ru"><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Fast Scalper</title><style>
:root{--bg:#101827;--card:#202b3b;--field:#3a4658;--muted:#aeb8c7;--blue:#2563eb;--green:#16a34a;--red:#dc2626;--gold:#f5c542;--line:#394659}*{box-sizing:border-box}body{font-family:system-ui;background:var(--bg);color:#fff;max-width:820px;margin:auto;padding:10px}.card{background:var(--card);border-radius:18px;padding:14px;margin:10px 0}button,input{border:0;border-radius:10px;padding:11px;font-size:15px}input{background:var(--field);color:#fff;border:1px solid #59677a;width:100%}button{font-weight:800;color:#fff;cursor:pointer}.two{display:grid;grid-template-columns:1fr 1fr;gap:7px}.paper{background:var(--blue)}.live{background:var(--green)}.stop{background:var(--red)}.em{background:#7f1d1d}.ghost{background:#475569;width:100%}.muted,.small{color:var(--muted);font-size:12px}.run{border:1px solid var(--line);border-radius:14px;padding:10px}.timer{font-size:20px;font-weight:900;font-variant-numeric:tabular-nums}.slot{display:grid;grid-template-columns:66px 1fr 70px;gap:6px;margin:8px 0}.clear{background:#475569;font-size:10px}.modes{display:grid;grid-template-columns:1fr 1fr;gap:4px;margin-top:4px}.mode{background:#526174}.active{box-shadow:0 0 0 3px var(--gold) inset,0 0 0 1px #fff}.amount{display:grid;grid-template-columns:1fr 1fr;gap:5px;margin-top:4px}.amount label{font-size:11px;color:var(--muted);display:flex;align-items:center;gap:5px}.amount input[type=checkbox]{width:20px}.rec,.result{border-bottom:1px solid var(--line);padding:8px 0}.recrow{display:grid;grid-template-columns:1fr auto auto;gap:5px}.pick{background:#475569}.details{display:none;color:var(--muted);font-size:12px}.details.open{display:block}.summary{display:grid;grid-template-columns:1fr 1fr;gap:6px}.metric{background:#182234;border-radius:10px;padding:8px}.metric b{display:block;font-size:16px}.pos{border:1px solid var(--line);border-radius:10px;padding:8px;margin:6px 0}.green{color:#86efac}.red{color:#fca5a5}.stage{background:#475569;border-radius:7px;padding:2px 6px;font-size:11px}@media(max-width:520px){.slot{grid-template-columns:58px 1fr 62px}.recrow{grid-template-columns:1fr auto}.recrow .pick{grid-column:2}.summary{grid-template-columns:1fr 1fr}}</style></head><body>
<h2>⚡ Fast Scalper</h2><p class="muted">Binance Spot • WebSocket radar • PAPER и LIVE независимы</p>
<div class="card"><b>Запуск</b><div class="two"><div class="run"><h4>PAPER</h4><button class="paper" onclick="run('PAPER')">▶ ЗАПУСТИТЬ PAPER</button><button class="stop" onclick="stop('PAPER')">■ STOP PAPER</button><div id="ps">⚪ остановлен</div><div id="pt" class="timer">00:00:00</div></div><div class="run"><h4>LIVE</h4><button class="live" onclick="run('LIVE')">▶ ЗАПУСТИТЬ LIVE</button><button class="stop" onclick="stop('LIVE')">■ STOP LIVE</button><button class="em" onclick="stop('LIVE',true)">⛔ EMERGENCY STOP</button><div id="ls">⚪ остановлен</div><div id="lt" class="timer">00:00:00</div></div></div><p class="muted">STOP = конец сессии: новые входы прекращаются, незавершённые заявки снимаются, уже купленные активы остаются в позициях и учитываются в итоговом балансе. EMERGENCY закрывает открытые позиции.</p></div>
<div class="card"><b>Binance API для LIVE</b><input id="key" placeholder="API Key" autocomplete="off"><input id="secret" type="password" placeholder="Secret Key" autocomplete="off"><p class="muted">Withdrawals не используются. Для LIVE — Spot Trading + IP restriction.</p></div>
<div class="card"><b>Бюджет</b><input id="capital" type="number" value="30" min="0.01" step="0.01"><span class="muted"> USDT</span></div>
<div class="card"><b>5 выбранных пар</b><p class="muted">Доля 0–100%. PAPER/LIVE видны постоянно.</p><div id="slots"></div></div>
<div class="card"><b>Топ-5 Fast Scalper</b><div id="top5">Загрузка…</div></div><div class="card"><b>20 кандидатов</b><button class="ghost" onclick="recs()">↻ ОБНОВИТЬ СПИСОК</button><div id="r">Загрузка…</div></div>
<div class="card"><b>Session Result — полный итог</b><div id="res">Нет активной сессии</div></div>
<script>
let slots=JSON.parse(localStorage.getItem('fsSlots')||'null')||Array.from({length:5},()=>({p:'',a:0,mode:'PAPER'}));const esc=s=>String(s||'').replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;');const fmt=v=>v==null?'—':Number(v).toFixed(6);const pad=n=>String(n).padStart(2,'0');
function save(){localStorage.setItem('fsSlots',JSON.stringify(slots))}function render(){slotsEl.innerHTML=slots.map((x,i)=>`<div class="slot"><button class="clear" onclick="clr(${i})">${i?'ОЧИСТИТЬ':'ОЧИСТИТЬ ВСЁ'}</button><div><input value="${esc(x.p)}" placeholder="Пара ${i+1}" oninput="slots[${i}].p=this.value.trim().toUpperCase().replace('-', '/');save()"><div class="modes"><button class="mode ${x.mode==='PAPER'?'active':''}" onclick="mode(${i},'PAPER')">PAPER</button><button class="mode ${x.mode==='LIVE'?'active':''}" onclick="mode(${i},'LIVE')">LIVE</button></div></div><input type="number" min="0" max="100" step="0.01" value="${x.a}" oninput="slots[${i}].a=+this.value;save()"></div>`).join('')}function clr(i){if(!i)slots=Array.from({length:5},()=>({p:'',a:0,mode:'PAPER'}));else slots[i]={p:'',a:0,mode:'PAPER'};save();render()}function mode(i,m){slots[i].mode=m;save();render()}function group(m){return slots.filter(x=>x.p&&x.mode===m)}function cfg(m){let x=group(m);return {capital:+capital.value,pairs:x.map(z=>z.p),allocations:x.map(z=>z.a),target_usdt:.30,min_usdt:.20,sl_pct:.5,max_hold:180,fee_pct:.1}}
function selectPair(s){let i=slots.findIndex(x=>!x.p);if(i<0)return alert('Все 5 строк заняты.');slots[i].p=s;save();render()}
function startSec(v){if(!v)return 0;return typeof v==='number'?(v>1e12?v/1000:v):Date.parse(v)/1000}function timer(el,status,d){let st=startSec(d.started_at),sec=st?Math.max(0,Date.now()/1000-st):0;document.getElementById(el).textContent=st?`${pad(Math.floor(sec/3600))}:${pad(Math.floor(sec%3600/60))}:${pad(Math.floor(sec%60))}`:'00:00:00';document.getElementById(status).textContent=d.running?'🟢 работает':'⚪ остановлен'}
async function run(m){let c=cfg(m),sum=c.allocations.reduce((a,b)=>a+b,0);if(!c.pairs.length)return alert('Нет выбранных '+m+' пар.');if(Math.abs(sum-100)>.01)return alert(m+': доли должны дать 100%. Сейчас '+sum.toFixed(2)+'%.');if(m==='LIVE'){c.api_key=key.value;c.api_secret=secret.value;if(!c.api_key||!c.api_secret)return alert('Для LIVE нужны API Key и Secret')}let q=await fetch('/api/'+m.toLowerCase()+'/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(c)}),d=await q.json();if(!q.ok)alert(d.detail||'Ошибка запуска');await refresh()}
async function stop(m,em=false){let q=await fetch('/api/'+m.toLowerCase()+'/'+(em?'emergency-stop':'stop'),{method:'POST'}),d=await q.json();if(!q.ok)alert(d.detail||'Ошибка остановки');await refresh()}
function report(d){let cls=v=>Number(v)>=0?'green':'red';let pos=(d.positions||[]).map(p=>`<div class="pos"><b>${esc(p.symbol)}</b> <span class="stage">${esc(p.stage||'OPEN')}</span><br><span class="small">вход ${fmt(p.entry_price??p.entry)} → текущая ${fmt(p.current_price)} • qty ${Number(p.amount||0).toFixed(8)}</span><br><span class="small">стоимость ${fmt(p.market_value)} USDT • нереализованный P/L <b class="${cls(p.unrealized_pnl)}">${fmt(p.unrealized_pnl)}</b> • возраст ${Math.floor(p.age_sec||0)}с / ${p.hold_seconds||'—'}с</span><br><span class="small">сигнал ${esc(p.signal||'—')} • fills ${(p.fills||[]).length}</span></div>`).join('')||'<span class="small">Нет открытых позиций</span>';let ord=(d.orders||[]).map(o=>`<div class="result"><b>${esc(o.symbol)}</b> • ${esc(o.side||'—')} • <span class="stage">${esc(o.status||'—')}</span> • ${Number(o.filled_amount||0).toFixed(8)} / ${Number(o.requested_amount||0).toFixed(8)} • fills ${(o.fills||[]).length}</div>`).join('')||'<span class="small">Нет активных заявок</span>';let tr=(d.trades||[]).slice().reverse().slice(0,10).map(t=>`<div class="result"><b>${esc(t.symbol)}</b> • ${fmt(t.entry??t.entry_price)} → ${fmt(t.exit??t.exit_price)} • P/L <b class="${cls(t.pnl??t.net_pnl)}">${fmt(t.pnl??t.net_pnl)}</b> • ${esc(t.reason||'—')}</div>`).join('')||'<span class="small">Сделок пока нет</span>';res.innerHTML=`<div class="summary"><div class="metric">Старт<b>${fmt(d.initial_balance)} USDT</b></div><div class="metric">Свободно<b>${fmt(d.free_usdt)} USDT</b></div><div class="metric">Стоимость<b>${fmt(d.equity_usdt)} USDT</b></div><div class="metric">NET<b class="${cls(d.net_pnl)}">${fmt(d.net_pnl)} USDT</b></div><div class="metric">Реализовано<b class="${cls(d.realized_pnl)}">${fmt(d.realized_pnl)}</b></div><div class="metric">Нереализовано<b class="${cls(d.unrealized_pnl)}">${fmt(d.unrealized_pnl)}</b></div></div><h4>Открытые позиции (${(d.positions||[]).length})</h4>${pos}<h4>Ордера / fills (${(d.orders||[]).length})</h4>${ord}<h4>Последние закрытые сделки</h4>${tr}${d.stop_type?`<p class="small">STOP: ${esc(d.stop_type)}</p>`:''}${d.error?`<p class="red small">Ошибка: ${esc(d.error)}</p>`:''}`}
async function refresh(){try{let [p,l,a,b]=await Promise.all([fetch('/api/session/report/PAPER'),fetch('/api/session/report/LIVE'),fetch('/api/paper/status'),fetch('/api/live/status')]);let pr=await p.json(),lr=await l.json();timer('pt','ps',pr);timer('lt','ls',lr);let d=pr.running?pr:lr.running?lr:(pr.started_at?pr:lr);report(d)}catch(e){}}
async function recs(){try{let d=await(await fetch('/api/recommendations?limit=20')).json();if(!d.candidates20?.length){r.textContent=d.radar_error?'Ошибка анализа: '+d.radar_error:'WebSocket подключается…';top5.textContent='WebSocket подключается…';return}top5.innerHTML=(d.top5||[]).map((x,i)=>`<div class="result"><b>#${i+1} ${x.symbol}</b> • ${x.signal} • вход ${fmt(x.estimated_entry)} → ${fmt(x.estimated_exit)} • <button class="pick" onclick="selectPair('${x.symbol}')">ВЫБРАТЬ</button></div>`).join('');r.innerHTML=d.candidates20.map((x,i)=>`<div class="rec"><div class="recrow"><div><b>#${i+1} ${x.symbol}</b> • ${x.signal}<br><span class="small">вход ${fmt(x.estimated_entry)} → выход ${fmt(x.estimated_exit)} • TF ${x.timeframe||'3m'} • ${x.hold_seconds||180}с</span></div><button class="pick" onclick="selectPair('${x.symbol}')">ВЫБРАТЬ</button></div><div class="details">SL ${fmt(x.estimated_stop)} • score ${Number(x.score||0).toFixed(2)} • 24ч ${Number(x.change_24h_pct||0).toFixed(2)}% • 3m ${Number(x.change_3m_pct||0).toFixed(3)}% • vol ×${Number(x.volume_ratio||1).toFixed(2)} • pumps ${x.pump_events||0}</div></div>`).join('')}catch(e){r.textContent='Ошибка анализа: '+e.message}}
const slotsEl=document.getElementById('slots');render();recs();refresh();setInterval(refresh,2000);setInterval(recs,10000);
</script></body></html>'''

@app.get('/',response_class=HTMLResponse)
def home():return HTML
